# Generated by Django 4.0.4 on 2022-12-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
